---
title: "Extracellular DNA promotes efficient extracellular electron transfer by pyocyanin in *Pseudomonas aeruginosa* biofilms."
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
    includes:
      before_body: index_files/header.html
      after_body: index_files/footer.html
  
---

```{r setup, echo = F, message = F, warning = F}
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE, echo = F, message=FALSE, warning=FALSE, fig.align="center", fig.retina = 2)

library(tidyverse)
library(knitr)
```

<br>

# Abstract

---

Extracellular electron transfer (EET), the process whereby cells access electron acceptors or donors that reside many cell lengths away, enables metabolic activity by microorganisms, particularly under oxidant-limited conditions that occur in multicellular bacterial biofilms. Although different mechanisms underpin this process in select organisms, a widespread strategy involves extracellular electron shuttles, redox-active metabolites that are secreted and recycled by diverse bacteria. How these shuttles catalyze electron transfer within biofilms without being lost to the environment has been a long-standing question. Here, we show that phenazine electron shuttles mediate efficient EET through interactions with extracellular DNA (eDNA) in *Pseudomonas aeruginosa* biofilms, which are important in nature and disease. Retention of pyocyanin (PYO) and phenazine carboxamide in the biofilm matrix is facilitated by binding to eDNA. In vitro, different phenazines can exchange electrons in the presence or absence of DNA and phenazines can participate directly in redox reactions through DNA; the biofilm eDNA can also support rapid ET between intercalators. Electrochemical measurements of biofilms indicate that retained PYO supports an efficient redox cycle with rapid EET and slow loss from the biofilm. Together, these results establish that eDNA plays a previously unrecognized role facilitating phenazine metabolic processes in *P. aeruginosa* biofilms, suggesting a model for how extracellular electron shuttles achieve retention and efficient EET in biofilms. 

<center>

Now published in *Cell* &nbsp; | &nbsp; [doi](https://doi.org/10.1016/j.cell.2020.07.006)

[bioRxiv preprint](https://www.biorxiv.org/content/10.1101/2019.12.12.872085v1) &nbsp; | &nbsp; [GitHub repository](https://github.com/DKN-lab/phz_eDNA_2019)

</center>

<br>

# Authors

---

* [Scott H. Saunders](https://scott-saunders.github.io/website/), Graduate student, Caltech BBE, Pasadena, CA
* [Edmund Tse](https://et-lab-hku.weebly.com/), Assistant Professor, University of Hong Kong, Hong Kong
* [Matthew Yates](https://scholar.google.com/citations?user=QjVhIr0AAAAJ&hl=en), Research Biologist, Naval Research Laboratory, Washington, D.C.
* [Fernanda Jimenéz Otero](http://orcid.org/0000-0003-1583-6495), Post-Doc, Naval Research Laboratory, Washington, D.C.
* [Scott Trammell](https://scholar.google.com/citations?user=KgxbIM8AAAAJ&hl=en), Scientist, Naval Research Laboratory, Washington, D.C.
* [Eric Stemp](https://www.msmu.edu/resources-culture/faculty-directory/faculty-members/stemp-eric.php), Professor, Mount St. Mary's, Los Angeles, CA
* [Jacqueline K. Barton](http://www.its.caltech.edu/~jkbgrp/), Professor, Caltech CCE, Pasadena, CA
* [Leonard M. Tender](https://scholar.google.com/citations?user=Rd6gIBUAAAAJ&hl=en), Scientist, Naval Research Laboratory, Washington, D.C.
* [Dianne K. Newman](http://dknweb.caltech.edu/Newman_Lab.html), Professor, Caltech BBE & GPS, Pasadena, CA

<br>


# Computational notebooks

----

These are notebooks generated in R. They fully reproduce the figures in the paper from the underlying raw data. These links will bring you to rendered html versions of the notebooks, but you are free to download the data and code from the [github repository](https://github.com/DKN-lab/phz_eDNA_2019) and run the notebooks on your own computer (given that you have R).

## Main figures

* [Figure 1.](https://scott-saunders.github.io/phz_eDNA_2019/code/figures/Fig_1/phz2019_Fig_1.html) Colony biofilms retain PYO and PCN, but not PCA.

* [Figure 2.](https://scott-saunders.github.io/phz_eDNA_2019/code/figures/Fig_2/phz2019_Fig_2.html) Phenazines bind extracellular DNA in vitro and in vivo.

* [Figure 3.](https://scott-saunders.github.io/phz_eDNA_2019/code/figures/Fig_3/phz2019_Fig_3.html) Constraints on phenazine electron transfer in vitro.

* [Figure 4.](https://scott-saunders.github.io/phz_eDNA_2019/code/figures/Fig_4/phz2019_Fig_4.html) Electrode grown biofilms exhibit PYO dependent electron transfer.

* [Figure 5.](https://scott-saunders.github.io/phz_eDNA_2019/code/figures/Fig_5/phz2019_Fig_5.html) PYO mediated electron transfer is faster than PYO loss from the biofilm.

* Figure 6 is a diagram that was made in Illustrator.


## Supplemental figures

* [Figure S1.](https://scott-saunders.github.io/phz_eDNA_2019/code/figures/supplement/Fig_S1/phz2019_Fig_S1.html) Colony biofilm images and controls.

* [Figure S2.](https://scott-saunders.github.io/phz_eDNA_2019/code/figures/supplement/Fig_S2/phz2019_Fig_S2.html) Phenazine - DNA binding assays.

* [Figure S3.](https://scott-saunders.github.io/phz_eDNA_2019/code/figures/supplement/Fig_S3/phz2019_Fig_S3.html) eDNA in colony biofilms.

* [Figure S4.](https://scott-saunders.github.io/phz_eDNA_2019/code/figures/supplement/Fig_S4/phz2019_Fig_S4.html) Phenazine electron transfer and time resolved spectroscopy.

* [Figure S5.](https://scott-saunders.github.io/phz_eDNA_2019/code/figures/supplement/Fig_S4/phz2019_Fig_S4.html) IDA biofilm phenazine production and retention.

* [Figure S6.](https://scott-saunders.github.io/phz_eDNA_2019/code/figures/supplement/Fig_S6/phz2019_Fig_S6.html) IDA $D_{ap}$ measurements.

* [Figure S7.](https://scott-saunders.github.io/phz_eDNA_2019/code/figures/supplement/Fig_S7/phz2019_Fig_S7.html) IDA $D_{loss}$ measurements. 

## Data processing

* [IDA ∆phz data](https://scott-saunders.github.io/phz_eDNA_2019/code/processing/IDA_dPHZ/IDA_dPHZ_processing.html)

* [IDA WT data](https://scott-saunders.github.io/phz_eDNA_2019/code/processing/IDA_WT/IDA_WT_processing.html)

* [IDA blank data](https://scott-saunders.github.io/phz_eDNA_2019/code/processing/IDA_blank/IDA_blank_processing.html)

