---
title: "Figure S3"
subtitle: 'Extracellular DNA promotes efficient extracellular electron transfer by pyocyanin in *Pseudomonas aeruginosa* biofilms.'
author: 'Scott H. Saunders, Edmund C.M. Tse, Matthew D. Yates, Fernanda Jiménez Otero, Scott A. Trammell, Eric D.A. Stemp, Jacqueline K. Barton, Leonard M. Tender and Dianne K. Newman'
output:
  html_document:
    theme: cosmo
    highlight: tango
    code_folding: show
    toc: yes
    keep_md: true
---

--------

# Notes

Fig S3A,B and D are images.

----

Setup packages and plotting for the notebook:

```{r setup, echo=T, message=FALSE, warning=FALSE}
# Load packages
library(tidyverse)
library(cowplot)
library(kableExtra)
library(broom)
library(modelr)

# Code display options
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=FALSE, echo = TRUE, message=FALSE, warning=FALSE, fig.align="center", fig.retina = 2)

# Load plotting tools
source("../../../tools/plotting_tools.R")


#Modify the plot theme
theme_set(theme_notebook())
```

# Fig. S3C

```{r}
pRdata <- read_csv('../../../../data/Spectroscopy/TOTO_DAPI_extracts.csv') %>% rename(TOTO=`1uM_TOTO_avg_(535nm)`,DAPI=`1uM_DAPI_avg_(445nm)`) %>%  
  gather(key='dye',value='fluor',TOTO, DAPI) %>% 
  separate(X1,sep=' ',c('added','Treatment','Replicate')) %>% 
  mutate(id=paste(added,Treatment,dye,sep = " ")) %>% 
  group_by(id) %>% 
  mutate(mean = ifelse(Replicate=='1',mean(fluor),NA))

# Plot layout
toto_plot <- ggplot(pRdata %>% filter(dye=='TOTO') %>% filter(id!="with ctDNA TOTO"),aes(x=id,y=fluor))+
  geom_col(aes(y=mean), fill = "light gray") +
  geom_jitter(height=0,width=0.1,shape =21, size = 1)

# Plot styling 
toto_plot_styled <- toto_plot +
  labs(x = NULL, y = 'TOTO-1 Fluorescence (A.U.)') + 
  scale_x_discrete(breaks = c('no ctDNA TOTO','no DNase TOTO','with DNase TOTO'), 
                   labels=c("-","+ buffer", "+ buffer\n+ DNase"))
    
toto_plot_styled     
```

# Fig. S3E

```{r}
df_biofilms <- read_csv("../../../../data/Spectroscopy/2019_11_22_std_wt_dphz_postCTdna.csv") %>%  gather(key = "well", value = "FluorInt", -wavelength)

df_meta <- read_csv("../../../../data/Spectroscopy/2019_11_22_well_metadata.csv")

df_toto <- left_join(df_biofilms, df_meta, by = c('well')) %>% filter(wavelength == 535)

df_toto %>% kable() %>% kable_styling(bootstrap_options = 'condensed') %>%
    scroll_box(width = "100%", height = "400px")
```

```{r}
bg_means <- df_toto %>% filter(strain != 'std' & tech_rep == 4) %>% group_by(strain) %>% summarise(mean = mean(FluorInt))

plot_eDNA <- ggplot(df_toto %>% filter(strain != 'std') %>% mutate(facet_labels = ifelse(strain =='dPHZ', paste0('\u0394','phz'), strain)), 
       aes(x = factor(tech_rep), y = FluorInt)) + 
  geom_line(data = . %>% filter(tech_rep<4), aes(group = bio_rep), color = 'light gray')+
  geom_hline(data = bg_means, aes(yintercept = mean), linetype = 2, color = 'light gray') +
  geom_point(data = . %>% filter(tech_rep<4), aes(fill = factor(ctDNA_added)), shape = 21) + 
  geom_jitter(data = . %>% filter(tech_rep==4), aes(x = 2), width = 1, shape = 21, color = 'light gray')+
  facet_wrap(~facet_labels, scales = 'free') + ylim(0, 30000) + guides(fill = F)

'\u0394'

# Plot styling

plot_eDNA_styled <- plot_eDNA + 
  labs(x = 'Technical replicates', y = 'TOTO-1 Fluorescence (A.U.)')

plot_eDNA_styled
```


# Create Figure

```{r}
theme_set(theme_figure())

fig_s3 <- plot_grid( toto_plot_styled,plot_eDNA_styled, align = 'hv', axis = 'tblr', ncol = 2, rel_widths = c(1,2), scale = 0.95, labels = c('C','E'), label_size = 12)

fig_s3

save_plot("../../../../figures/supplement/phz2019_Fig_S3.pdf", fig_s3, base_width = 7, base_height = 2)
```

----

```{r}
sessionInfo()
```